import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider, authMiddleware } from '@clerk/nextjs'
import "./globals.css";
import dashboardpage from "./users/dashboard/[[...dashboard]]/page";
import UserProfilecomponent from "./components/users/userprofile";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gym app",
  description: "Generated by QWERTY",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (  
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
